#!/usr/bin/perl -w

use lib '/home/aragorn/perl/lib/perl5/site_perl';
use lib '/home/aragorn/preview/lib';
use Benchmark;
use Time::HiRes qw(gettimeofday tv_interval);
my ($t1, $t01) = (new Benchmark, [gettimeofday]);
use strict;
use warnings;
use CGI qw(:standard escape escapeHTML -oldstyle_urls);
use Daum::ShortenURL;

our @DEBUG;

my $q       = new CGI; $q->charset('utf-8'); # for proper escapeHTML
my $url     = param('u') || "";
my $referer = param('referer') || "";
my $fetch   = 1;
my $save    = 1;
my $shorten = new Daum::ShortenURL;

print $q->header(-charset=>'utf-8', -type=>'text/html');

my ($row,$res) = $shorten->lookup_local($url,$referer);

if ($q->self_url =~ m/debug/) {
  $fetch   = param('fetch') || 0;
  $save    = param('save')  || 0;
}

print p({class=>'debug'}, "executes fetch_and_save($url,$referer), fetch=$fetch")."\n"
  if not exists $row->{url_id} and $fetch and $q->self_url =~ m/debug/;

if (not exists $row->{url_id} and $fetch and $save) {
  ($row,$res) = $shorten->fetch_and_save($url,$referer);
} elsif (not exists $row->{url_id} and $fetch) {
  ($row,$res) = $shorten->fetch($url,$referer);
}

my ($title,$original_url) = map { $row->{$_} || "" } qw(original_title original_url);
$title = "제목이 없습니다" unless $title;

print <<END;
<p class="title">$title</p>
<p class="url">$original_url</p>
END

my ($t2, $t02) = (new Benchmark, [gettimeofday]);
print p({class=>'debug'}, "elapsed time=", tv_interval($t01, $t02), "secs")."\n";
print p({class=>'debug'}, "benchmark=", timestr(timediff($t2, $t1)))."\n";
print p({class=>'debug'}, "loaded from local db")."\n" if $row->{url_id};
print p({class=>'debug'}, "fetch=$fetch")."\n";
if ($q->self_url =~ m/debug/) {
  foreach my $k ( keys %{$row} )
  { next if $k =~ m/^_/; print p({class=>'debug'}, "row{$k} = ". escape($row->{$k}) ), "\n"; }
  foreach ( @DEBUG ) { print p({class=>'debug'}, $_),"\n"; }
  foreach ( $shorten->debug ) { print p({class=>'debug shorten'}, $_),"\n"; }
  print p({class=>'debug'}, "reload ",
          a({href=>"?".$q->query_string},
            $q->unescape($q->script_name ."?". $q->query_string))),"\n";
}

exit;

