#!/usr/bin/perl -w

use strict;
use warnings;
use utf8;
use CGI qw(:standard escape escapeHTML -oldstyle_urls);
use CGI::Carp qw(fatalsToBrowser);
use LWP::Simple qw(!head);
use XML::Parser;
use List::Util qw(min max);
use Data::Dumper;
use Daum;
use Daum::Breeze2;
use POSIX;

Daum::Breeze2::init_benchmark();

our @DEBUG;
binmode STDOUT, ":encoding(UTF-8)";

push @DEBUG, Daum::Breeze2::check_clock("elapsed time 1");

my $bz2     = new Daum::Breeze2;
my $image_url_default = "http://archive.search.daum-img.net/twitter.com/beyond_00.png";
my $base_url = "http://%s/search.2/search.py?coll=sch_realtime&enc=utf8&&p=1&n=%s&req=all&q=%s";
my $q       = new CGI; $q->charset('utf-8'); # for proper escapeHTML
my $query   = param('q') || "iphone"; utf8::decode($query);
my $page    = param('p') || "1";
my $count   = param('n') || "10";
my $where   = param('w') || "tot";
my $source_id = param('source_id') || "";
my $server  = param('server') || "10.30.127.227:8080";

our ($max_height, $min_height, $max_width,  $min_width  ) = (40, 2, 23, 2);

print $q->header(-charset=>'utf-8', -type=>'text/plain');

push @DEBUG, Daum::Breeze2::check_clock("elapsed time 2");

print "<!--\n";
my $search_url = sprintf($base_url, $server, $count, escape($query)); #, $page);
$search_url .= "&source_id=$source_id" if $source_id;
print "search_url=$search_url\n";

my $xml = LWP::Simple::get($search_url); utf8::decode($xml);

push @DEBUG, Daum::Breeze2::check_clock("elapsed time 3");

my $result = $bz2->parse_xml_result($xml,$page);

push @DEBUG, Daum::Breeze2::check_clock("after parse   ");

map { print "debug: ", $_, "\n"; } @DEBUG;
map { print "result $_: ", $result->{$_}, "\n"; } sort keys %{$result};

print "-->\n";

print <<END;
<!-- 실시간검색Coll -->
<style type="text/css">
END

print <<END;

</style>
END

my $issue_level = $result->{issue_level};
my $issue_score = sprintf("%2.2f", $result->{issue_score});
my $issue_values = $result->{issue_values};
my $slope_max   = sprintf("%2.3f", $result->{statistical_data}->{slope_max});
my $total_count = $result->{total_count};

my %cnt;
map { $cnt{$_} = Daum::Breeze2::commify($result->{$_} || 0); } qw(total_count page_start page_end);
print <<END;
<div id="liveSearchColl" class="liveSearchColl">
 <div class="collTitle" style="height: auto;">
   <h2 class="fL">&nbsp;</h2>
   <!--span class="tit_add lsp fL"> 
     <span class="ico_updating fL" id="icoUpdate" style="display:block;"><img width="10" height="10" alt="업데이트중" src="http://imgsrc.search.daum-img.net/search_all/2010/icon/ico_live_search_updating.gif"></span> 
     <span class="ico_stand fL" id="icoStand" style="display:none;"></span> 
 
     <span class="g_tit txt_update fL" id="statusRealTimeRun">업데이트 중 - </span> 
     <span class="ico_stop fL" id="btnRealTimeRun1"><a class="base fwn" href="javascript:_jsChangeRealTimeFlag();">일시 정지</a></span> 
     <span class="ico_play fL" id="btnRealTimeRun2" style="display:none"><a class="base fwn" href="javascript:_jsChangeRealTimeFlag();">다시 시작</a></span>
   </span-->
   <span class="tit_add">
     <span class="g_tit">level $issue_level :$issue_score</span> /
     <span class="g_tit">$issue_values</span> /
     <span class="g_tit">slope_max:$slope_max</span> /
     <span class="g_tit"><a href="$search_url">$server</a></span> /
     <!--span class="g_tit">$cnt{page_start}-$cnt{page_end}</span> / -->
     <span class="g_tit">n=$count</span> /
     <span class="g_tit">총 $cnt{total_count}\건</span>
   </span> 
 </div>
END

print get_timeline($result->{statistical_data}, $total_count);
=rem
print get_timeline($result->{statistical_data}, 20000);
print get_timeline($result->{statistical_data}, 5000);
print get_timeline($result->{statistical_data}, 2000);
print get_timeline($result->{statistical_data}, 1600);
print get_timeline($result->{statistical_data}, 1200);
print get_timeline($result->{statistical_data}, 800);
print get_timeline($result->{statistical_data}, 400);
print get_timeline($result->{statistical_data}, 200);
print get_timeline($result->{statistical_data}, 100);
print get_timeline($result->{statistical_data}, 50);
print get_timeline($result->{statistical_data}, 20);
=cut

print <<END;
 <div class="live_search_body">
   <ul class="list_live_search" id="realTimeList">
END

my $page_count = $result->{page_count} || 0;
$page_count = 4 if $where eq "tot" and $page_count > 4;
$page_count = 40 if $page_count > 40;

#foreach my $doc ( map(+( $result->{ds}->[$_] ), 0..($page_count-1)) )
foreach my $doc ( @{$result->{ds}} )
{
  my ($docid, $title, $description, $description2, $doc_url,
      $index_time, $index_date, $score, $source_id,
      $nickname, $display_name, $pub_time, $pub_date, $doc_rank, $user_id, $display_url,
      $image_url, $channel_url, $channel_id)
   = map { utf8::decode($doc->{$_}); $doc->{$_} || "" }
       qw(docid title description description2 doc_url 
          index_time index_date score source_id
          nickname display_name pub_time pub_date doc_rank user_id display_url
          image_url channel_url channel_id);
  my $short_score = sprintf("%.7f", $score);
  my ($doc_link, $source_class) = ("트위터 원문보기", "ico_twiter");
  ($doc_link, $source_class) = ("Daum요즘 원문보기", "ico_yozm") if $source_id eq "yozm";
  $image_url = $image_url_default unless $image_url;
  map { print "<!-- $_ = $doc->{$_} -->\n" } sort keys %{$doc};

  print <<END;
<li class="mb_basic">
  <div class="box_con">
   <span class="wrap_time"><a href="$doc_url" target="_blank" class="bl_sstit"><span id="getRealIndexTime_0"><script type="text/javascript">try{document.write(_jsMakeRealTimeDate('$pub_time'));}catch(e){}</script></span></a>
     <span class="bl_sstit">$short_score</span>
     <span class="bl_sstit">$source_id</span>
   </span>
END
  
  print <<"END" if $source_id eq "twitter" or $source_id eq "yozm";
   <span class="wrap_photo">
     <a href="$doc_url" target="_blank"><img src="$image_url" width="48" height="48" alt=""/></a>
   </span>
END

  if ($source_id eq "cafe" or
      $source_id eq "news" or
      $source_id eq "board" or
      $source_id eq "blog") {
    print <<END;
   <span class="wrap_con">
     <span class="txt_con">
       <span class="link_tit"><a href="$doc_url" class="tit_u gulim" target="_blank">$title</a></span>
       $description
     </span><!--class="txt_con"-->
     <span class="txt_source">
END
    print <<"END" if $nickname;
       <span class="g_tit">$nickname</span>
       <span class="vline">&nbsp;|&nbsp;</span>
END

    print <<END;
       <span class="source"><a href="$display_url" target="_blank" class="g_tit">$display_name</a></span>
     </span>
   </span><!--class="wrap_con"-->
   <div class="clr"></div>
  </div>
  <div class="bg_top"></div>
  <div class="bg_bottom"></div>
</li>
END
  } else {
    print <<END;
   <span class="wrap_con">
     <span class="base">$title</span><!--class="base"-->
     <span class="txt_source">
       <a href="$channel_url" target="_blank" class="g_tit">$user_id</a>
       <span class="vline">&nbsp;|&nbsp;</span>
       <span class="$source_class"><a href="$doc_url" target="_blank" class="g_tit">$doc_link</a></span>
     </span>
   </span><!--class="wrap_con"-->
   <div class="clr"></div>
  </div>
  <div class="bg_top"></div>
  <div class="bg_bottom"></div>
</li>
END

  }
}

if ($where eq "tot")
{
  my $query_escaped = escape($query);
  print <<END;
    </ul>
  </div><!--class="live_search_body"-->
  <div class="clr"></div>
  <div class="moreArea"><a href="?w=dir&m=sch_realtime&q=$query_escaped">실시간검색 더보기</a></div>
</div><!--id="liveSearchColl"-->
<!-- end 실시간 검색 Coll --> <div id="line"></div><hr/>
END
} else {
  print <<END;
    </ul>
  </div><!--class="live_search_body"-->
  <div class="clr"></div>
</div><!--id="liveSearchColl"-->
END
}

=rem
print <<END;
<script type="text/javascript"> 
var _jsRealTimeFirstTime = 20000;
 
  _jsRealTimeFirstTime = 10000;
 
try{
  _jsGetTimeObject.push({id:"0", time:"1285583171000"});
  _jsGetTimeObject.push({id:"1", time:"1285583101000"});
  _jsGetTimeObject.push({id:"2", time:"1285583070000"});
  _jsGetTimeObject.push({id:"3", time:"1285583055000"});
  _jsGetTimeObject.push({id:"4", time:"1285583041000"});
  _jsGetTimeObject.push({id:"5", time:"1285582980000"});
  _jsGetTimeObject.push({id:"6", time:"1285582959000"});
  _jsGetTimeObject.push({id:"7", time:"1285582878000"});
  _jsGetTimeObject.push({id:"8", time:"1285582828000"});
  _jsGetTimeObject.push({id:"9", time:"1285582435000"});
  _jsRealTimeSearchExec = new _jsRealTimeSearch();
 
  if(daumSF.Browser.getCookie("detailOptionBox")=="true"){
    daumSF.Browser.setCookie("detailOptionBox","",0);
    _jsDetailOptionShowHide();
  }
}catch(e){}
</script>
END
=cut

push @DEBUG, Daum::Breeze2::check_clock("elapsed time x");

print "<!--\n";
if (url(-absolute=>1) =~ m/debug/) {
  foreach ( @DEBUG ) { print p({class=>'debug'}, $_); }
  my $reload_link = $q->unescape($q->script_name ."?". $q->query_string); utf8::decode($reload_link);
  print p({class=>'debug'}, "reload ",
          a({href=>"?".$q->query_string}, $reload_link));
}
print "-->\n";

exit;

#print qq(<div class="bar" style="" title="max: $max_slot_min"></div>);
sub bar_width {
  my $value = shift;
  my $width = int ( 4.2 * log(0.01+$value/3) / log(4.0) );
  $width = max($min_width, $width);
  return min($max_width, $width);
}

sub get_timeline
{
  my $stat = shift;
  my $total_count = shift;
  my @html;
  push @html, <<END;
<style type="text/css">
.visualClear { clear: both; }

div.timeline-container {
  position: relative;
}

div.timeline-container div.panel {
  position: absolute;
  width: 90px; height: 15px;
  font-size: 9pt;
  xxoutline: 1px dotted red;
  margin: 5px 0 15px 0;
  padding-top: 40px;
  xxdisplay: none;
}
div.timeline-container div.panel.prev {
  position: relative;
  float: left;
  font-size: 6pt;
  width: 15px;
  margin: 0 0 5px 0;
  padding-top: 45px;
}

div.timeline-container div.bar {
  background-color: transparent;
  cursor: pointer;
  float: left;
  margin-right: 12px;
  position: relative;
  width: 15px;
  height: 10px;
  z-index: 10;
  outline: 0px solid gray;
}

div.timeline-container div.bar.twitter { background: #33f; width: 100%; outline: 0; }
div.timeline-container div.bar.others  { background: #ccc; width: 100%; outline: 0; }

</style>
<div class="timeline-container">
 <div class="panel prev">&lt;&lt;</div>
END

  my @panels = map {
    my $time = time - $_*90*60;
    my $string = POSIX::strftime("%p %l:%M", localtime($time));
    utf8::decode($string);
    $string;
  } ( 4,3,2,1 );

  push @html, <<END;
 <div class="panel" style="left:  15px; width: 090px; ">$panels[0]</div>
 <div class="panel" style="left: 105px; width: 090px; ">$panels[1]</div>
 <div class="panel" style="left: 195px; width: 090px; ">$panels[2]</div>
 <div class="panel" style="left: 285px; width: 090px; ">$panels[3]</div>
END

  my $max_slot_min = max(
    map { $stat->{$_} }
    map { qq(slot_min_).$_ }
      ( 330,300,270,240,210,180,150,120,90,60,30,0 )
  );

  push @html, map {
    my $bar_count    = $stat->{qq(slot_min_$_)} || 0;
    my $twitter_count = $stat->{qq(twitter_min_$_)} || 0;
    my $others_count  = $bar_count - $twitter_count;

    my $bar_height     = int($max_height * $bar_count / $max_slot_min);
    my $twitter_height = int($max_height * $twitter_count / $max_slot_min);
    my $others_height  = $bar_height - $twitter_height;
    my $bar_top = $max_height - $bar_height - 5;
    $bar_height += 2 * $min_height + 1;
    $twitter_height += $min_height;
    $others_height  += $min_height;

    my $width  = bar_width($total_count);
    #int($max_width * $max_slot_min ) + $min_width;
    #$height += int( $max_height * ( exp(1/$sqrt*log(0.01+$count)) / exp(1/$sqrt*log(1+$max_count)) ) );

    my $twitter_top = 0;
    my $others_top  = 1;

    my $margin_right = 28 - $width;
    qq(<div class="bar" style="height: $bar_height px; width: $width px; top: $bar_top px; margin-right: $margin_right px; " title="$_: $bar_count">)
    . qq(<div class="bar twitter" style="height: $twitter_height px; top: $twitter_top px;" title="twitter $_: $twitter_count / $bar_count"></div>)
    . qq(<div class="bar others" style="height: $others_height px; top: $others_top px; " title="others $_: $others_count / $bar_count"></div>)
    .qq(</div>);
  } ( 360,330,300,270,240,210,180,150,120,90,60,30,0 );

  push @html, <<END;
 <div class="visualClear"></div>
</div>
END

  return @html;
}

1;
