#!/usr/bin/perl -w

use lib '../../lib';
use Benchmark;
use Time::HiRes qw(gettimeofday tv_interval);
my ($t1, $t01) = (new Benchmark, [gettimeofday]);
use strict;
use warnings;
use utf8;
use CGI::Carp qw(warningsToBrowser fatalsToBrowser);
use CGI qw(:standard escape escapeHTML -oldstyle_urls);
use LWP::UserAgent;
use LWP::Simple qw(!head);
use Unicode::String qw(utf8);
use Daum::FederatedSearch;

binmode STDOUT, ":encoding(UTF-8)";

my @BENCHMARK = ();
my ($t2, $t02) = (new Benchmark, [gettimeofday]);
push @BENCHMARK, p("before new CGI:", tv_interval($t01, $t02), timestr(timediff($t2, $t1)));

our $q     = new CGI; $q->charset('utf-8'); # for proper escapeHTML

print $q->header(-charset=>'utf-8', -type=>'text/html');
#warningsToBrowser(1);
 
($t2, $t02) = (new Benchmark, [gettimeofday]);
push @BENCHMARK, p("before new FederatedSearch:", tv_interval($t01, $t02), timestr(timediff($t2, $t1)));

my $fsearch = new Daum::FederatedSearch(query=>$q, benchmark=>$t1, gettimeofday=>$t01);

($t2, $t02) = (new Benchmark, [gettimeofday]);
push @BENCHMARK, p("after new FederatedSearch:", tv_interval($t01, $t02), timestr(timediff($t2, $t1)));

$fsearch->handler('realTimeColl', \&realTimeColl);
$fsearch->handler('liveSearchColl', \&realTimeColl);
$fsearch->handler('snsColl', \&snsColl);
$fsearch->add_tab('sns', '소셜웹', 'w=sns&q=%s&enc=utf8&nul_search=btn');

if ($fsearch->fetch_search_result($q)) {
  ($t2, $t02) = (new Benchmark, [gettimeofday]);
  push @BENCHMARK, p("after fetch_search_result:", tv_interval($t01, $t02), timestr(timediff($t2, $t1)));

  print $fsearch->html_head;
  print $fsearch->html_body;

  print qq(<div class="clr"></div><div style="position: relative; top: 160px;">);
  ($t2, $t02) = (new Benchmark, [gettimeofday]);
  push @BENCHMARK, p("after print html_body:", tv_interval($t01, $t02), timestr(timediff($t2, $t1)));

  map { print $_, "\n"; } @BENCHMARK;
  if (self_url =~ m/debug/o) {
    map { print $_, "\n"; } $fsearch->debug;

    my ($t2, $t02) = (new Benchmark, [gettimeofday]);
    print p("elapsed=", tv_interval($t01, $t02))."\n";
    print p("benchmark=", timestr(timediff($t2, $t1)))."\n";
  }
  print qq(</div>);
  print $fsearch->html_body_close;
} else {
  print $fsearch->status_line;
}

exit;
##############################################################################

sub snsColl {
  my $self = shift;
  my $query = $q->param('q') || "";
  my $utf8_query = Daum::FederatedSearch::utf8_string($query);
  my $query_escaped = escape($utf8_query);
  my $where = $q->param('w') || "";
  my $reply = param('reply') || "";
  my $page  = 1;
  my $full_url = url(-full=>1); $full_url =~ s/\w+$//o;
  my $base_url = $full_url . "sns?w=$where&q=%s&p=%s&reply=%s";
  my $search_url = sprintf($base_url, escape($query),$page,$reply);
  my $html = LWP::Simple::get($search_url);
  utf8::decode($html);

  my $separator = qr{<li class="doc">|</li><!--class="doc"-->}o;
  my @items = split(/($separator)/o, $html);
  foreach ( @items ) {
    next if m/$separator/o;
    my ($class,$source) = ("","");
    m!<span\sclass="nick">\s*<a\shref="([^"]+)"!isogx and $source = $1;
    $class = "twitter" if index($source, "twitter.com")> 0;

    s{ ( <span \s class="base"> )      # $1
       ( .{0,500} )                    # $2
       ( </span><!--class="base"--> )  # $3
     }
    ! $1.make_autolink($2,$class,$source).$3 !isogxe;
  }
  my $modified = join("<!-- XYZ -->", @items);

  return $modified;

  return $html;

}

##############################################################################

sub realTimeColl {
  my $self = shift;
  my $html = shift;

  my $separator = qr{<\/li>\s*<li class="mb_basic">|<li class="mb_basic">|<\/li>}o;
  my @items = split(/($separator)/o, $html);
  foreach ( @items ) {
    next if m/$separator/o;
    my ($class,$source) = ("","");
    m!<span\sclass="wrap_time">\s*<a\shref="([^"]+)"!isogx and $source = $1;
    $class = "twitter" if index($source, "twitter.com")> 0;

    s{ (?<=<span \s class="base"> )   # not $1
       ( .{0,500} )                    # $1
       (?=</span> \s* <span \s class="txt_source">)  # not $2
     }
    ! make_autolink($1,$class,$source) !isogxe;
  }
  my $modified = join("<!-- XYZ -->", @items);

  return $modified;
}

sub make_autolink {
  $_ = shift;
  my $class  = shift || "";
  my $source = shift || "";

  # @username link
  s{ ( ^ | \s | [^A-Za-z0-9] )     # $1
     \@                           
     ([A-Za-z0-9_]+)               # $2
   } ! qq($1\@<a href="http://twitter.com/$2" target="_blank" class="g_tit twitter">$2</a>) !isogxe
   if $class eq "twitter";

  # #keyword link
  s{ ( ^ | \s | [^A-Za-z0-9&] )     # $1
     \#
     ([A-Za-z0-9_\w]+ | \w+_ )     # $2
   } ! qq(^$1^<a href="http://twitter.com/search?q=)
       .escape("#$2").
       qq(" target="_blank" class="g_tit twitter">#$2</a>) !isogxe
   if $class eq "twitter";

  # 이미 URL에 링크가 걸려 있는 경우
  s{ <a \s+ class="stit" 
        \s+ href=" \s*
        (https?://
         [\w-]+ (?: \.[\w-]+)+ (?: / [^\s\)\>\<]{0,200} )?
        ) \s* "                       # $1
        \s+ target="_blank"
        (?: \s+ class="stit" )?> \s*
        ( (?: \w|<b>|</b>|[:/-]|[^\s\)\>\<] ){0,200}
        )                             # $2
        \s* </a>
   } ! url_link($1,$2,$class,$source) !isogxe;
         # https?://
         # [\w-]+ (?: \.[\w-]+)+ (?: / [^\s\)\>\<]{1,200} )?

  # 텍스트로 URL만 있는 경우
  #s{$Daum::FederatedSearch::url_pattern} !url_link($1,$class,$source)!ioxge;
  s{
     (?xi)
       #\b  # replaced by line below
       (\s | (?<!url)\( | \< | ^) # \K # look-behind assertion # FIXME: \K requires perl 5.9.5
     (                       # Capture 1: entire matched URL
       (?:
         https?://               # http or https protocol
         |                       #   or
         www\d{0,3}[.]           # "www.", "www1.", "www2." … "www999."
         |                           #   or
         [a-z0-9.\-]+[.][a-z]{2,4}/  # looks like domain name followed by a slash
       )
       (?:                       # One or more:
         [^\s()<>]+                  # Run of non-space, non-()<>
         |                           #   or
         \(([^\s()<>]+|(\([^\s()<>]+\)))*\)  # balanced parens, up to 2 levels
       )+
       (?:                       # End with:
         \(([^\s()<>]+|(\([^\s()<>]+\)))*\)  # balanced parens, up to 2 levels
         |                               #   or
         [^\s`!()\[\]\{\};:'".,<>?«»“”‘’]        # not a space or one of these punct chars
       )
     )
  } !$1.url_link($2,$2,$class,$source)!ioxge;
   
  return $_;
}

sub url_link {
  my $src    = shift || "";
  my $url    = shift || "";
  my $class  = shift || "";
  my $source = shift || "";
  $src = "http://$src" unless $src =~ m#^https?://#o;

  my $href = "redirect?u=". escape($src) ."&referer=". escape($source); 
  my $rel  = "get?u=". escape($src) ."&fmt=html&referer=". escape($source); 
  $rel  = "get?u=". escape($src) ."&fmt=html&fetch=1&save=0&referer=". escape($source)
    if self_url =~ m/debug/o;

  return qq(<a href="$href" target="_blank" class="stit auto tips $class" rel="$rel"
 xxtitle="about this link:">$url</a>);
}


##############################################################################
# XXX url encoding by charset
# UTF-8  - 월드컵 - %EC%9B%94%EB%93%9C%EC%BB%B5
# EUC-KR - 월드컵 - %BF%F9%B5%E5%C4%C5
##############################################################################
