#!/usr/bin/perl -w

use strict;
use warnings;
use utf8;
use CGI qw(:standard escape escapeHTML -oldstyle_urls);
use CGI::Carp qw(fatalsToBrowser);
use LWP::Simple qw(!head);
use XML::Parser;
use Data::Dumper;
use Daum::Breeze2;

Daum::Breeze2::init_benchmark();

our @DEBUG;
binmode STDOUT, ":encoding(UTF-8)";

push @DEBUG, Daum::Breeze2::check_clock("elapsed time 1");

my $bz2     = new Daum::Breeze2;
my $image_url_default = "http://archive.search.daum-img.net/twitter.com/beyond_00.png";
#my $base_url = "http://10.31.125.234:7777/front/search.py?enc=utf8&q=%s";
my $base_url = "http://10.30.144.200:7777/front/search.py?enc=utf8&n=800&q=%s&p=%s&child=y&submit=yes";
#my $base_url = "http://110.45.208.13:8080/xml/144.200.iphone.xml?q=%s&p=%s";
my $q       = new CGI; $q->charset('utf-8'); # for proper escapeHTML
my $query   = param('q') || "iphone"; utf8::decode($query);
my $page    = param('p') || "1";
my $where   = param('w') || "tot";

#print $q->header(-charset=>'utf-8', -type=>'text/html');
print $q->header(-charset=>'utf-8', -type=>'text/plain');

push @DEBUG, Daum::Breeze2::check_clock("elapsed time 2");

print "<!--\n";
my $param_reply = param('reply') || "";
my $search_url = sprintf($base_url, escape($query), $page); # unless utf8::is_utf8($query);
$search_url = sprintf("http://10.30.144.200:7777/front/search.py?enc=utf8&reply=%s&submit=yes",
              $param_reply) if $param_reply;
print "search_url=$search_url\n";

my $xml = LWP::Simple::get($search_url); utf8::decode($xml);

push @DEBUG, Daum::Breeze2::check_clock("elapsed time 3");

my $result = $bz2->parse_xml_result($xml,$page);

push @DEBUG, Daum::Breeze2::check_clock("after parse   ");

map { print "debug: ", $_, "\n"; } @DEBUG;
map { print "result $_: ", $result->{$_}, "\n"; } sort keys %{$result};

print "-->\n";

print <<END;
<!-- 소셜웹Coll -->
<style type="text/css">
/*
#snsColl li {outline: 1px solid red;}
*/

#snsColl .collTitle {overflow:visible;margin-bottom:12px;}
#snsColl li {display:block;float:left;width:719px;}
#snsColl li.write {height:0px;margin-bottom:0px;overflow:hidden;line-height:0px;font-size:0px;}
#snsColl li .divAniBox {width:100%;padding-bottom:18px;line-height:16px;}
#snsColl li .thumb {margin:1px 15px 0 0;}
#snsColl li .thumb img {border:1px solid #ECECEC;}
#snsColl li .desc {padding-top:2px;line-height:18px;}
#snsColl li .info {padding-top:2px;font:12px/13px AppleGothic,gulim,sans-serif;}

/*
#snsColl li .commentBox {float:left;width:635px;background:url("http://imgsrc.search.daum-img.net/search_all/2009/image/bg_realsearch.gif") repeat-y -630px 0px;}
#snsColl li .commentBody {padding:0px 15px 0px 15px;background:url("http://imgsrc.search.daum-img.net/search_all/2009/image/bg_realsearch.gif") no-repeat 0px 0px;}
#snsColl li .commentFoot {width:100%;height:10px;font-size:0px;line-height:0px;background:url("http://imgsrc.search.daum-img.net/search_all/2009/image/bg_realsearch.gif") no-repeat -1260px bottom;}
*/

#snsColl li .commentBox {float:left;width:654px;}
#snsColl li .commentBody {padding:0px 0px 0px 0px; }
#snsColl li .commentFoot {width:100%;height:0px;font-size:0px;line-height:0px; }

#snsColl li .commentBody .desc {padding-top:0px;line-height:18px;}

#snsColl li .commentBody .info {padding-top:2px;font:12px/13px AppleGothic,gulim,sans-serif;}
#snsColl li .textBox {padding-top:3px;}
#snsColl li .getTime {color:#6671FF;font-size:12px;text-decoration: none;}
#snsColl li a.getTime:hover {text-decoration: underline;}
#snsColl li a.getTime:hover span {text-decoration: underline;}
#snsColl li .nick {color:#7A7A7A;}
#snsColl li .source {color:#7A7A7A;}
#snsColl li .vline {font-size:11px;}
#snsColl li .hline {border-top:#e2e2e2 solid 1px;font-size:0px;height:12px;margin-top:12px;}
#snsColl li ul.cluster li {width: 100%;}

#snsColl li .icoYozm {padding-left:14px;padding-bottom:1px;background: url("http://imgsrc.search.daum-img.net/search_all/2010/icon/ico_svico.gif") no-repeat -2px 0px;}
#snsColl li .icoMetwo {padding-left:16px;background: url("http://imgsrc.search.daum-img.net/search_all/2010/icon/ico_svico.gif") no-repeat 0px -34px;}
#snsColl li .icoTwitter {padding-left:13px;padding-top:1px;background: url("http://imgsrc.search.daum-img.net/search_all/2010/icon/ico_svico.gif") no-repeat -2px -66px;}

#snsColl #btnRealTimeRun1, #snsColl #btnRealTimeRun2 {text-decoration: none;font:12px dotum;letter-spacing: -1px}
#snsColl #btnRealTimeRun1:hover, #snsColl #btnRealTimeRun2:hover {text-decoration: underline;}
#snsColl .hide {display:none !important;}

#snsColl .relationTip {margin-top:21px;padding-top:14px;border-top:1px solid #ECECEC;}
* html #snsColl .relationTip {padding-top:15px;}
#snsColl .relationTip p b {color:#0307C3;}
#snsColl #statusRealTimeRun {margin-left:11px;font-weight:normal;font-family: dotum;letter-spacing: -1px}

#clusterResultUL .cpLink {margin-top:2px;} 
#clusterResultUL span.cluster.fst {margin-top:7px;} 
#clusterResultUL .cluster {
margin-top:6px;padding-left:13px;
background:url("http://imgsrc.search.daum-img.net/search_all/2009/icon/cb_search_icon_2009.gif") no-repeat 1px -860px}
#clusterResultUL .cluster_more {
margin-top:6px;display:inline-block;color:#6671FF;font-size:12px;margin-left:13px;}
/*#clusterResultUL .mlink {
width:auto;margin-left:0;font-size:12px;font-family:AppleGothic,"새굴림","굴림",gulim,sans-serif;vertical-align:0;}*/
#clusterResultUL.uccUl li {margin-top:18px;} 
#clusterResultUL.uccUl li.fst {margin-top:0;} 
#newsColl .mlink {
width:auto;margin-left:0;font-size:12px;
font-family:AppleGothic,"새굴림","굴림",gulim,sans-serif;
padding-top:0px;vertical-align:0;
letter-spacing:0;
background:transparent url(http://imgsrc.search.daum-img.net/search_all/2009/icon/search_icon_2009.gif) no-repeat scroll 62px -2012px;}
#newsColl ul.uccUl dd span.tit.mainTit {float:left;margin-bottom:3px;}
#newsColl .mlink.viewLink {background-position:30px -2012px; padding:0px 21px 0 0;text-decoration:none;}
#newsColl .mlink:visited {text-decoration:none !important;}
#newsColl .mlink:hover {text-decoration:underline !important;}

#snsColl .collTot {margin-left: 17px;}
#snsColl ul.cluster {margin-top: 4px;}
#snsColl ul.cluster li { padding: 3px 0 3px 0; }
#snsColl ul.cluster li.indent {
  padding-left: 15px;
  background: url(http://imgsrc.search.daum-img.net/search_all/2009/icon/cb_search_icon_2009.gif) no-repeat 1px -857px;
}
#snsColl ul.cluster .cluster {font-weight: bold; color: #33d; }
#snsColl ul.cluster .cluster.dimmed { color: #88b; }
END

print <<END;

#DFMiniSlider {display:inline;margin-left:13px;}
#DFMiniSlider #sliderWrap {padding:0;border-bottom:0;}
#DFMiniSlider #sliderWrap .sliderWrap {float:left;position:relative;width:106px;height:20px;}
#DFMiniSlider #sliderWrap .sliderWrap .handle {width:16px;height:15px;cursor:pointer;}
#DFMiniSlider #sliderWrap .sliderWrap .handle img {position:relative;top:1px;}
#DFMiniSlider #sliderWrap .sliderWrap #sliderHandle.handle img {left:-6px;}
#DFMiniSlider #sliderWrap .sliderWrap #sliderHandle2.handle img {left:0px;}
#DFMiniSlider #sliderWrap .sliderWrap #activeBg {position:absolute;left:20px;height:3px;top:4px;background:url(http://img-contents.daum-img.net/movie/2008_home/photo/img_slide_on.gif) repeat-x;font-size:0;cursor:pointer;}
#DFMiniSlider #sliderWrap .sliderWrap #track5 {width:106px;height:17px;background:url(http://imgsrc.search.daum-img.net/search_all/2009/image/img_timeline_bar.gif) no-repeat 0 -84px;cursor:pointer;}
#DFMiniSlider #sliderWrap .leftTxt {float:left;margin-right:18px;margin-top:2px;white-space:nowrap;}
#DFMiniSlider #sliderWrap .rightTxt {float:left;margin-left:10px;margin-top:1px;white-space:nowrap;}
 
#DFMiniSlider .tooltip {position:absolute;width:81px;height:24px;background:url('http://imgsrc.search.daum-img.net/search_all/2009/image/rank_tooltip.gif') no-repeat 0 0;}
#DFMiniSlider .tooltip.r0 {top:-23px;left:-40px;background-position:0 0;}
#DFMiniSlider .tooltip.r1 {top:-23px;left:-14px;background-position:0 -59px;}
#DFMiniSlider .tooltip.r2 {top:-23px;left:12px;background-position:0 -118px;}
#DFMiniSlider .tooltip.r3 {top:-23px;left:38px;background-position:0 -177px;}
#DFMiniSlider .tooltip.r4 {top:-23px;left:64px;background-position:0 -236px;}

</style>
END

if ($where eq "tot")
{
print <<END;
<div id="snsColl">
 <div class="collTitle">
   <h2 class="fL">소셜웹</h2>
 </div>
 <div class="collTot" style="height: inherit;">
  <ul id="snsList" style="height: inherit;">
END
} else {
  my $slider = html_DFMiniSlider();
  my %cnt;
  map { $cnt{$_} = Daum::Breeze2::commify($result->{$_} || 0); } qw(total_count page_start page_end);
print <<END;
<div id="snsColl">
 <div class="collTitle">
   <h2 class="mt2 fL">소셜웹</h2>
   <span class="fL">$slider</span>
   <span id="resultCntArea" class="titleLinkFr">&nbsp;
     <em class="nrl g_tit">$cnt{page_start}-$cnt{page_end} / 총 $cnt{total_count}\건</em></span>
   <div class="clr"></div>
 </div>
 <div class="collTot" style="height: inherit;">
  <ul id="snsList">
END
}

my $page_count = $result->{page_count} || 0;
$page_count = 4 if $where eq "tot" and $page_count > 4;
$page_count = 30 if $page_count > 30;

foreach my $doc ( map(+( $result->{ds}->[$_] ), 0..($page_count-1)) )
{
  my ($docid, $edocid, $content, $url, $image_url, $channel_url,
      $writedttm, $sns_name, $reply, $retweet, $child_count )
   = map { utf8::decode($doc->{$_}); $doc->{$_} || "" }
       qw(docid edocid content url image_url channel_url writedttm sns_name reply retweet child_count);
  my $write_time = Daum::relative_time($writedttm, $result->{serverdttm});
  my $channel_link = "&nbsp;";
  my $source_class = "icoTwitter";
  $image_url = $image_url_default unless $image_url;
  my @clusters;
  @clusters = @{ $doc->{clusters} }
    if defined $doc->{clusters} 
       and ref $doc->{clusters} eq "ARRAY";
  print <<END;
<!--BEGIN-->
<li class="doc">
  <div class="thumb fL">
   <a href="$channel_url" target="_blank"><img src="$image_url" width="48" height="48" alt/></a>
  </div>
  <div class="commentBox">
    <span class="base">$content</span><!--class="base"-->
    <p class="info">
      <span class="source $source_class">
        <a href="$channel_url" target="_blank" class="g_tit">$channel_link</a>
      </span>
      <span class="vline">|</span>
      <a href="$url" target="_blank" class="getTime">$write_time
        <span id="getRealIndexTime_0" class="getTime">
        <script type="text/javascript">try{document.write(_jsMakeRealTimeDate(''));}catch(e){}</script>
        </span>
      </a>
      <span class="vline">|</span>
      <span class="nick">
        <a href="$url" target="_blank" class="g_tit">$sns_name</a>
      </span>
END
  if ($reply) {
    print <<END;
      <span class="vline">|</span>
      <span class="nick">
        <a href="$channel_url" target="_blank" class="g_tit">답글보기</a>
      </span>
END
  }
  print <<END;
    </p>
END

  print qq(<ul class="cluster">\n);
  my $clusters = @clusters;
  if ( $clusters > 0 ) {
    print qq(<li class="related-summary">관련글 <a href="" class="cluster">$clusters</a>건\n);
  } else {
    print qq(<li class="related-summary">관련글 <span class="cluster dimmed">$clusters</span>건\n);
  }
  $child_count = 0 unless $child_count;
  if ($child_count > 0) {
    my $href = "?w=sns&q=".escape($query)."&reply=".escape($edocid);
    print <<END;
      <span class="vline">|</span>
      <span class="child">
        <a href="$href" class="g_tit">이 글에 달린 답글보기</a>
      </span>
END
  }
  print <<END;
    </li>
END

  foreach my $clustered ( @clusters )
  {
    my ($docid, $edocid, $content, $url, $image_url, $channel_url, $writedttm, $sns_name )
     = map { utf8::decode($clustered->{$_}); $clustered->{$_} || "" }
       qw(docid edocid content url image_url channel_url writedttm sns_name);
    my $cut = Daum::Breeze2::strhncpy($content, 60);
    my $write_time = Daum::relative_time($writedttm, $result->{serverdttm});
    print <<END;
    <li class="indent"><span class="base">$cut</span><!--class="base"-->
      <span class="vline">|</span>
      <a href="$url" target="_blank" class="getTime">$write_time
        <span id="getRealIndexTime_0" class="getTime">
        <script type="text/javascript">try{document.write(_jsMakeRealTimeDate(''));}catch(e){}</script>
        </span>
      </a>
      <span class="vline">|</span>
      <span class="nick">
        <a href="$channel_url" target="_blank" class="g_tit">$sns_name</a>
      </span>
    </li>
END
  }
  print qq(</ul><!--class="cluster"-->\n);

  print <<END
  </div><!--class="commentBox"-->
  <div class="hline clr"></div>
</li><!--class="doc"-->
<!--END-->
END
}

if ($where eq "tot")
{
  my $query_escaped = escape($query);
  print <<END;
  <div class="clr"></div>
  </ul><!--id=snsList"-->
 </div>
 <div class="moreArea">
   <a href="?w=dir&m=sns&q=$query_escaped">소셜웹 더보기</a>
 </div>
</div>
<!-- end 소셜웹Coll -->
<!-- 구분라인 -->
<div id="line"></div>
<hr>
<!-- end 구분라인 -->
END
} else {
  print <<END;
  <div class="clr"></div>
  </ul><!--id=snsList"-->
 </div>
</div>
<!-- end 소셜웹Coll -->
END
}

#print pre(Dumper($result));

push @DEBUG, Daum::Breeze2::check_clock("elapsed time x");

if (url(-absolute=>1) =~ m/debug/) {
  foreach ( @DEBUG ) { print p({class=>'debug'}, $_); }
  my $reload_link = $q->unescape($q->script_name ."?". $q->query_string); utf8::decode($reload_link);
  print p({class=>'debug'}, "reload ",
          a({href=>"?".$q->query_string}, $reload_link));
}
print <<END;
<div id="line"></div>
<hr>
END

exit;


sub html_DFMiniSlider
{
  return <<'END';

<div id="DFMiniSlider" class="DFMiniSlider fL">
  <div id="sliderWrap">
    <div id="rankSelTxtArea1" class="leftTxt fwn fs12 "><img class="valign" src="http://imgsrc.search.daum-img.net/search_all/2009/icon/icon_check.gif" width="11" height="12"> 정확도 <span class="vline"> | </span><a id="rankSelTxtRecen" href="javascript:;" class="stit_nv">최신</a></div>
    <div id="rankSelTxtArea2" class="leftTxt fwn fs12 hide"><a id="rankSelTxtAccu" href="javascript:;" class="stit_nv bulletDot">정확도</a><span class="vline"> | </span><img class="valign" src="http://imgsrc.search.daum-img.net/search_all/2009/icon/icon_check.gif" width="11" height="12"> 최신</div>
    <div class="sliderWrap">
      <div id="track5"></div>
      <div id="sliderHandle" class="handle hide"><img src="http://imgsrc.search.daum-img.net/search_all/2009/btn/btn_lank_cursor.gif" width="13" height="17"></div>
      <div id="rankSliderTooltip" class="hide"></div>
    </div>
  </div>
</div>

<script type="text/javascript" defer="defer"> 
var rankingSlider = (function(){
  // 핸들러 ID
  var handleId = "sliderHandle";
 
  // 정확도 최신 showhide 영역 Element
  var rankSelTxtArea1El = daumSF.$E("rankSelTxtArea1");
  var rankSelTxtArea2El = daumSF.$E("rankSelTxtArea2");
  // 정확도 최신 Element
  var rankSelTxtRecenEl = daumSF.$E("rankSelTxtRecen");
  var rankSelTxtAccuEl = daumSF.$E("rankSelTxtAccu");
  // 랭킹슬라이더툴팁 Element
  var rankSliderTooltipEl = daumSF.$("rankSliderTooltip");
 
  // track의 총길이
  var trackLength = 106;
  // 촤우측 이동공간 영역 설정
  var handleLeftScopeStart = 0;
  var handleRightScopeEnd = trackLength;
 
  // 년도 기준
  var startIdx = 1;
  var endIdx = 5;
 
  // 기타요소 객체
  var track = daumSF.$("track5");
 
  // 화면 초기화
  var init = function(){
    daumSF.$(handleId).style.display="block";
    //graduation(startYear);
  };
 
  // 위치값으로 인덱스 계산
  var getIdxByPos = function( pos ){
    var distIdx = endIdx - startIdx;
    var distPos = handleRightScopeEnd - handleLeftScopeStart;
    var idxPerPixel = distIdx / distPos;
    var result = startIdx + Math.floor( idxPerPixel * ( pos - handleLeftScopeStart ) );
    return result;
  };
 
  // 인덱스값으로 위치값 계산
  var getPosByIdx = function( idx ){
    var distIdx = endIdx - startIdx;
    var distPos = handleRightScopeEnd - handleLeftScopeStart;
    var pixelPerIdx = distPos / distIdx ;
    var result = Math.floor( pixelPerIdx * ( idx - startIdx ) );
    return result;
  };
 
  // 초기값 설정
 
  var initIdxValue="3"
  if(daumSF.getParam("sort")) {
    if(daumSF.getParam("sort")=="" || daumSF.getParam("sort")=="step1" || daumSF.getParam("sort")=="recency" || daumSF.getParam("sort")=="rrecency") initIdxValue="5"
    else if(daumSF.getParam("sort")=="step2") initIdxValue="4";
    else if(daumSF.getParam("sort")=="step3") initIdxValue="3";
    else if(daumSF.getParam("sort")=="step4") initIdxValue="2";
    else if(daumSF.getParam("sort")=="step5" || daumSF.getParam("sort")=="accuracy") initIdxValue="1";
  }
  var handleInitPos = getPosByIdx( initIdxValue );
 
  var toolTipTimeOutId;
  var setTooltipBox = function(_idx){
    rankSliderTooltipEl.className = "tooltip r"+_idx;
    rankSliderTooltipEl.style.display="block";
  }
  var hideTooltip = function(){
    rankSliderTooltipEl.style.display="none";
  }
 
  // 좌측 핸들러 정의
  var handle = daumSF.widget.slider( handleId );
  handle.setScopeX({
    init : handleInitPos
  }).addEventListener({
    type : "onMouseDown",
    func : function(){
      handle.setScopeX({
        start : handleLeftScopeStart,
        end : handleRightScopeEnd
      });
    }
  }).addEventListener({
    type : "onMouseMove",
    func : function(){
      setTooltipBox(Math.round(handle.getPos().left/(trackLength/4)));
    }
  }).addEventListener({
    type : "onMouseUp",
    func : function(){
      handle.setPosX((Math.round(handle.getPos().left/(trackLength/4))*26));
      _jsSearchByTune(Math.round(handle.getPos().left/(trackLength/4)));
    }
  }).addEventListener({
    type : "onMouseOut",
    func : function(){
      toolTipTimeOutId = setTimeout('daumSF.$E("rankSliderTooltip").style.display="none"',2000);
    }
  }).addEventListener({
    type : "onMouseOver",
    func : function(){
      setTooltipBox(Math.round(handle.getPos().left/(trackLength/4)));
    }
  }).run();
 
  // 트랙 정의
  daumSF.Event.addEvent( track, "mousedown", function(e){
    var coords = daumSF.getCoords( track.id );
    var startX = e.clientX;
    var origX = this.offsetLeft + coords.left;
    var deltaX = startX - origX;
    handle.setPosX((Math.round(deltaX/(trackLength/4))*26));
    track.focus();
    _jsSearchByTune(Math.round(handle.getPos().left/(trackLength/4)));
  }, false );
  daumSF.Event.addEvent( track, "mousemove", function(e){
    var coords = daumSF.getCoords( track.id );
    var startX = e.clientX;
    var origX = this.offsetLeft + coords.left;
    var deltaX = startX - origX;
    setTooltipBox(Math.round(deltaX/(trackLength/4)));
  }, false );
  daumSF.Event.addEvent( track, "mouseout", function(e){
    toolTipTimeOutId = setTimeout('daumSF.$E("rankSliderTooltip").style.display="none"',2000);
  }, false );
 
  // 최신 클릭
  daumSF.addEvent( rankSelTxtRecenEl, "click", function(ev){
    var target = daumSF.getElement( ev );
    handle.setPosX(getPosByIdx(5));
    rankSelTxtArea1El.style.display="none";
    rankSelTxtArea2El.style.display="block";
    _jsSearchByTune(4);
    smartLog(this, "s=BL&a=RKBL&pg=1&r=1&p=6&rc=1", null);
    return gLink(null, "RKBL", "1", "6");
  }, false );
  // 정확도 클릭
  daumSF.addEvent( rankSelTxtAccuEl, "click", function(ev){
    var target = daumSF.getElement( ev );
    handle.setPosX(getPosByIdx(3));
    rankSelTxtArea1El.style.display="block";
    rankSelTxtArea2El.style.display="none";
    _jsSearchByTune(2);
    smartLog(this, "s=BL&a=RKBL&pg=1&r=1&p=7&rc=1", null);
    return gLink(null, "RKBL", "1", "7");
  }, false );
 
  init();
 
})();
 
function _jsSearchByTune(_opt){
  var sType = "";
  switch(_opt){
    case 0 :
      sType="step5";
      break;
    case 1 :
      sType="step4";
      break;
    case 2 :
      sType="step3";
      break;
    case 3 :
      sType="step2";
      break;
    case 4 :
      sType="step1";
      break;
  }
  if(_opt >=3){
    daumSF.$E("rankSelTxtArea1").style.display="none";
    daumSF.$E("rankSelTxtArea2").style.display="block";
  }else{
    daumSF.$E("rankSelTxtArea1").style.display="block";
    daumSF.$E("rankSelTxtArea2").style.display="none";
  }
  blogParameters.sort = sType;
  doSearchByAjax();
}
 
function _chgSortOrder(_opt){
  if(_opt==0){
    //과거순
    blogParameters.sort = "rrecency";
    daumSF.$E("sortBtnOldOrder").style.display="none";
    daumSF.$E("sortBtnNewOrder").style.display="block";
    doSearchByAjax();
  }else if(_opt==1){
    //최신순
    blogParameters.sort = "step1";
    daumSF.$E("sortBtnOldOrder").style.display="block";
    daumSF.$E("sortBtnNewOrder").style.display="none";
    doSearchByAjax();
  }
}
</script>
END

}

1;
